import asyncio
import inspect

import click

from aredis_om.model.migrations.migrator import Migrator


async def _run_migrations(module: str, dry_run: bool = False):
    migrator = Migrator(module=module)
    await migrator.detect_migrations()

    if dry_run:
        return await migrator.run(dry_run=True)

    if migrator.migrations:
        print("Pending migrations:")
        for migration in migrator.migrations:
            print(migration)

        if input("Run migrations? (y/n) ") == "y":
            return await migrator.run()
    return None


@click.command()
@click.option("--module", default="aredis_om")
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Print the migrations that would be applied without running them.",
)
def migrate(module: str, dry_run: bool):
    result = _run_migrations(module, dry_run=dry_run)
    # This branch is intentional: the sync mirror generated by unasync calls the
    # same wrapper, but there `_run_migrations()` is no longer awaitable.
    if inspect.isawaitable(result):
        return asyncio.run(result)  # type: ignore[arg-type]
    return result
