services:
    redis:
        image: "redis:8-alpine"
        restart: always
        ports:
            - "6380:6379"

    valkey:
        image: "valkey/valkey:9-alpine"
        restart: always
        ports:
            - "6381:6379"
