services:
    redis:
        image: "redis:alpine"
        restart: always
        ports:
            - "6380:6379"

    valkey:
        image: "valkey/valkey-bundle:alpine"
        restart: always
        ports:
            - "6381:6379"
