import asyncio
import inspect

import click

from redis_om.model.migrations.migrator import Migrator


def _run_migrations(module: str):
    migrator = Migrator(module=module)
    migrator.detect_migrations()

    if migrator.migrations:
        print("Pending migrations:")
        for migration in migrator.migrations:
            print(migration)

        if input("Run migrations? (y/n) ") == "y":
            return migrator.run()
    return None


@click.command()
@click.option("--module", default="redis_om")
def migrate(module: str):
    result = _run_migrations(module)
    # This branch is intentional: the sync mirror generated by unasync calls the
    # same wrapper, but there `_run_migrations()` is no longer awaitable.
    if inspect.isawaitable(result):
        return asyncio.run(result)
    return result
